-- Least-privilege runtime grants for Voice/Vapi tools.
GRANT USAGE ON SCHEMA voice TO voice_runtime, agent_runtime;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA voice TO voice_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA voice TO agent_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA voice TO voice_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA voice GRANT SELECT, INSERT, UPDATE ON TABLES TO voice_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA voice GRANT SELECT ON TABLES TO agent_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA voice GRANT USAGE, SELECT ON SEQUENCES TO voice_runtime;
