-- Least-privilege runtime grants for CRM tools.
GRANT USAGE ON SCHEMA crm TO crm_runtime, agent_runtime;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA crm TO crm_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA crm TO agent_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA crm TO crm_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA crm GRANT SELECT, INSERT, UPDATE ON TABLES TO crm_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA crm GRANT SELECT ON TABLES TO agent_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA crm GRANT USAGE, SELECT ON SEQUENCES TO crm_runtime;
